@startuml component.puml
title ESP32 Internet Radio - Component Diagram

skinparam backgroundColor white
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 70
skinparam ranksep 70

component "ESP Radio Application" as FW #Application

component "FreeRTOS" as RTOS
component "ESP-ADF" as ADF
component "ESP-IDF Platform" as IDF
component "NVS" as NVS
component "LittleFS" as LFS

FW -(0- IDF #line:Red;text:Red : ""I2C API""
FW -(0- IDF #line:Green;text:Green : ""I2S API""
FW -(0- IDF #line:Blue;text:Blue : ""GPIO API""
FW -(0- LFS #line:DarkBlue;text:DarkBlue : ""FS API""
FW -(0- NVS #line:Purple;text:Purple : ""NVS API""
FW -(0- IDF #line:Brown;text:Brown : ""Networking API""
FW -(0- RTOS #line:DarkGoldenRod;text:DarkGoldenRod : ""RTOS API""
FW -(0- ADF #line:DarkCyan;text:DarkCyan : ""Audio API""

ADF ..> IDF : uses
RTOS <.. IDF : includes
NVS <.. IDF : includes
LFS <.. IDF : includes

@enduml
