@startuml seq_station_display.puml
title ESP32 Internet Radio - Sequence Diagram (Station Display)

actor "app_main" as APP
box "Core" #LightBlue
participant "AppContext" as CTX
participant "AppController" as CTRL
participant "UiTask\n(IUiSink)" as UITASK
end box

box "Services" #LightGreen
participant "UiService" as UISVC
participant "StationRepository" as REPO
end box

box "Adapters" #LightYellow
participant "OledSsd1306Display\n(IDisplay)" as DISP
participant "EspI2cBus\n(II2cBus)" as I2C

end box
box "ESP-IDF" #LightGray
participant "ESP-IDF I2C driver" as IDF
end box

== Init ==
activate APP
APP -> CTX ++: AppContext.init()
CTX -> I2C ++: init()
I2C -> IDF ++: i2c_new_master_bus(busConfig)
return res
I2C -> IDF ++: i2c_master_probe(0x3C)
return res
return res
CTX -> DISP ++: init()
DISP -> I2C ++: writeBytes(init sequence)
I2C -> IDF ++: i2c_master_transmit(dev=0x3C, bytes[init])
return res
return res
return res
CTX -> REPO ++: init()
return res
CTX -> UISVC ++: init()
return res
CTX -> UITASK ++: init()
return res
CTX -> CTRL ++: init()

== Render Stations ==
CTRL -> UITASK ++: post(AppEvent::STATIONS, selected=0)
CTRL -> CTX : res
CTX -> APP : res
deactivate CTRL
deactivate CTX
UITASK -> UISVC ++: onEvent(STATIONS)
UISVC -> REPO ++: getStations()
return stations
UISVC -> DISP ++: showFramebuffer(stationsFB)
DISP -> I2C ++: writeBytes(page/col cmds)
I2C -> IDF ++: i2c_master_transmit(dev=0x3C, bytes[page/col])
return res
return res
DISP -> I2C ++: writeBytes(framebuffer with 0x40 ctrl)
I2C -> IDF ++: i2c_master_transmit(dev=0x3C, bytes[data])
return res
return res
return res
return res

deactivate UISVC
deactivate DISP
deactivate I2C
deactivate IDF
deactivate UITASK
deactivate CTRL

APP -> APP: infinite loop

@enduml